### ISSUE TITLE
update electron

### ISSUE THREAD

**Issue by roscoevanderboom** [jschr/electron-react-redux-boilerplate#82] opened 2019-09-24 17:06 UTC
I notice the project is using Electron 3.0.0. This has not caused any issues. I'm just wondering if you will be updating to the latest version.

I tried updating to latest electron, but then boilerplate doesn't load. I've also updated all dependencies and devDependencies but it nothing loads unless Electron is version 3

**Comment by pronebird** [comment] 2019-09-24 17:08
It should work with Electron 4.x but everything above v5 needs some tweaking due to chrome-sandbox binary issue. I'll update the boilerplate when I have time.

**Comment by roscoevanderboom** [comment] 2019-09-24 17:11
Awesome. Thanks a lots. I really like using it, and staying up-to-date is my OCD.

**Comment by roscoevanderboom** [comment] 2019-09-25 03:59
If you need help, I'd be happy to give it a shot. I have free time atm. I'm still learning and this could be an great challenge for me. Just point me in the right direction. I've forked and added some code to your boilerplate. 

https://github.com/roscoevanderboom/electron-react-redux-materialUI-boilerplate

**Comment by pronebird** [comment] 2019-09-25 11:37
@roscoevanderboom Great, then go ahead and give it a try! It's really not that hard to update to the most recent Electron 6. 

There are two things we need to consider which are both related to Linux platform:

1. Newer Electron comes with `chrome-sandbox` which requires root permissions to run Electron. So I guess, while in development, adding `--no-sandbox` when launching electron is reasonable. See: https://github.com/mullvad/mullvadvpn-app/blob/master/gui/tasks/electron.js#L7

1. When in production, in order to run the app using `chrome-sandbox`, the correct permissions have to bet set for the `chrome-sandbox` binary, i.e `chmod 4775 chrome-sandbox` should do it. 

    Apparently there are different ways to solve this issue, either by `chmod`-ing the `chrome-sandbox` file during installation or before packing the deb/rpm which I believe should preserve the filesystem permissions. I'd look into adding a script to do that at `afterPack` stage.

    Here's how we use `afterPack` at Mullvad VPN via programmatic interface to electron-builder: https://github.com/mullvad/mullvadvpn-app/blob/master/gui/tasks/distribution.js#L181
    I believe it should be possible to use `afterPack` without moving the whole electron-builder config into Javascript like we do at Mullvad VPN but we do have a complex configuration so we benefit from dynamic configuration.

**Comment by roscoevanderboom** [comment] 2019-09-28 04:57
I made my first attempts, without any luck. Testing on Windows10, only development mode. If I can manage this, I'll try Linux configs and production.

Changes:

-  `--no-sandbox`  to electron.js 
https://github.com/roscoevanderboom/electron-react-redux-materialUI-boilerplate/blob/master/tasks/electron.js

- `webPreferences: {
      sandbox: false
    }` to index.js for good measure
https://github.com/roscoevanderboom/electron-react-redux-materialUI-boilerplate/blob/master/app/main/index.js

- update to latest Electron

- `electron: '6.0.10'` to babel.config.js
https://github.com/roscoevanderboom/electron-react-redux-materialUI-boilerplate/blob/master/babel.config.js

**Comment by pronebird** [comment] 2019-09-28 10:36
@roscoevanderboom afaik you don't have to modify `webPreferences`, i.e no need for `sandbox: false` in there. If you use node integration in renderer processes, then you need to enable it via `webPreferences: { nodeIntegration: true }`. I think that should do it.

**Comment by roscoevanderboom** [comment] 2019-09-28 11:03
I tried that. Everything starts fine. Runs through all the build scripts down to watch-html...but no browser window.

Any other dependencies that might need to be updated?

**Comment by pronebird** [comment] 2019-09-28 11:31
@roscoevanderboom not that I can think of. Do you see any errors in the output?

**Comment by roscoevanderboom** [comment] 2019-09-28 11:32
No. It all looks perfect. Just no browser window is created

**Comment by pronebird** [comment] 2019-09-28 11:58
@roscoevanderboom that should do it https://github.com/jschr/electron-react-redux-boilerplate/commit/a6b0de4e654080fa7f031e71bcd66c7863330973

But I am still missing the Linux distribution part. I'll look into it now.

**Comment by roscoevanderboom** [comment] 2019-09-28 12:22
My version didn't work. I must have missed something. But I cloned yours and it all works fine. I will start to add all my changes ( material UI and others ) and see if there are any conflicts. 

Thanks for sorting it out so quickly!

**Comment by roscoevanderboom** [comment] 2019-09-28 12:31
There is no rush on the Linux build fix. My app is still far from production builds.

This is what I'm working on btw: 
https://github.com/roscoevanderboom/MultiChain-Client

**Comment by roscoevanderboom** [comment] 2019-09-28 12:37
I have some exec files that I include in the project. Do I put them in the app/main and then add the to assets.js + gulp to have them included in the build process?

**Comment by pronebird** [comment] 2019-09-28 12:47
@roscoevanderboom 

>There is no rush on the Linux build fix. My app is still far from production builds.
>
>This is what I'm working on btw:
>https://github.com/roscoevanderboom/MultiChain-Client

very cool 👍 

I see that `electron-builder` had the relevant fix merged in their master https://github.com/electron-userland/electron-builder/commit/7c2881e52930082136f6e4b7950c3611e0e07100. 

So I suppose there is no need to fix anything on our side at this point.

>I have some exec files that I include in the project. Do I put them in the app/main and then add the to assets.js + gulp to have them included in the build process?

If you have other binaries that you'd like to include in the app, then I guess you better put them in `dist-assets/`, then configure electron-builder to copy them, i.e:

```yml
extraResources:
      - from: "dist-assets/my-binary.exe"
         to: "."
```

Then in development you just make sure that you use the right path to binary, i.e:

```
const executable = process.env.NODE_ENV === 'development'
    ? path.resolve(__dirname, '../../dist-assets/my-binary.exe')
   : process.resourcesPath

execFile(executable, args, { windowsHide: true }, function (error, stdout, stderr) {
 // ...
})
```

**Comment by roscoevanderboom** [comment] 2019-09-28 12:53
Great. Thanks. I will tweak it a bit, as there will be 3 folders with binaries for win / linux / mac. But I get what you mean. That helps a lot!

**Comment by pronebird** [comment] 2019-09-28 12:59
@roscoevanderboom we do the same thing at Mullvad VPN, so feel free to glance at how we organize our configuration: https://github.com/mullvad/mullvadvpn-app/blob/master/gui/tasks/distribution.js#L84

**Comment by roscoevanderboom** [comment] 2019-09-28 13:08
wow...that's awesome. It's gonna take me a while to wrap my head around those configs. I'm definitely putting this link in the todo list for my app!

**Comment by roscoevanderboom** [comment] 2019-09-28 14:37
My apologies...i made a mistake. I tested on Linux ( Lubuntu 18 ) and everything works. On windows10 though there is no browser window. When I thought it was working, I hadn't actually updated the package.json.

**Comment by pronebird** [comment] 2019-09-28 14:51
@roscoevanderboom I'm pretty sure we have it working on Windows 10. I would have to find out where it breaks. I am pretty sure we had it working before.

**Comment by roscoevanderboom** [comment] 2019-09-28 14:52
I've clone and pushed changes. 

https://github.com/roscoevanderboom/electron-react-redux-materialUI-boilerplate

**Comment by pronebird** [comment] 2019-09-28 14:57
Can you try running Electron with `--disable-gpu` or add `app.commandLine.appendSwitch('--disable-gpu')` in the `main/index.js` and see if that makes a difference?

**Comment by roscoevanderboom** [comment] 2019-09-28 15:03
I tried both but same result.


![Capture](https://user-images.githubusercontent.com/39595310/65818464-78c0e000-e209-11e9-992a-a62b59c9e7bb.PNG)

**Comment by roscoevanderboom** [comment] 2019-09-28 15:11
I've also updated to node from v10 to v12. Just in case but no change

**Comment by pronebird** [comment] 2019-09-29 16:37
@roscoevanderboom I am not able to reproduce the issue that you experience. The latest master works well on my Windows 10 installation with Node.js v12.11 on MacBook.

**Closed by pronebird** 2019-09-29 16:37 UTC
