### ISSUE TITLE
"npm run develop" works, but doesn't render ReactComponent.

### ISSUE THREAD

**Issue by wildorwilliamgit** [jschr/electron-react-redux-boilerplate#104] opened 2020-10-02 08:11 UTC
I am excited to find your repo because this is using react and redux with electron.
There are many repo with relation to react-redux boilerplate using electron, but I choosed this because this is very good and very useful.
Thanks for your efforts.

When I execute "npm run develop" in command, I can see the electron window, but can't see any ReactComponent such as Login page. There are already react component like login, loggedin, as you made.

In app/index.html
From:
<div id="app"></div>
<script src="./app.js" data-container="#app"></script>
To:
<div id="app" style="background-color='red'; width:200px;height:200px;"></div>
<script src="./app.js" data-container="#app"></script>

As a result, I can see the changes with style of app section.
But I can't see the works of script tag including reactcomponents.
So right now, I don't see the app/renderer/components/Login.js Component. 
So there is empty after executing "npm run develop". And can't see any erros. What's problem?
please give me any clue with relation to this.

**Note:**
1)I think it is related to c:/users/<username>/.electron. Right now I have no files there.
If there should be the files, plz let me know the file's url.
2)Maybe it is related to the version problem.

Thanks a lot. WildorWilliam

**Comment by pronebird** [comment] 2020-10-02 08:27
Hi,

Can you please check if there are any errors printed to console or dev tools console?

Cheers, 
Andrey

**Comment by wildorwilliamgit** [comment] 2020-10-02 08:52
![Uploading 1111111111111.png…]()

Thanks for your response. Thanks again.
The above is electron app errors.

The below is console error in VS code.


 electron-react-redux-boilerplate@0.0.0 develop F:\10_Freelancer\Huateng Fang\electron_result\commcat\103\electron-react-redux-boilerplate
> gulp develop
[15:45:54] Using gulpfile F:\10_Freelancer\Huateng Fang\electron_result\commcat\103\electron-react-redux-boilerplate\gulpfile.js
[15:45:54] Starting 'develop'...
[15:45:54] Starting 'clean'...
[15:45:54] Finished 'clean' after 10 ms
[15:45:54] Starting 'copy-html'...
[15:45:54] Finished 'copy-html' after 54 ms
[15:45:54] Starting 'dev-build-scripts'...
[15:45:59] Finished 'dev-build-scripts' after 5.21 s
[15:45:59] Starting 'start-hotreload'...
[15:46:00] Finished 'start-hotreload' after 486 ms
[15:46:00] Starting 'inject-hotreload'...
[15:46:00] Finished 'inject-hotreload' after 10 ms
[15:46:00] Starting 'start-electron'...
[15:46:00] Finished 'start-electron' after 17 ms
[15:46:00] Starting 'watch-main-scripts'...
[15:46:00] Starting 'watch-renderer-scripts'...
[15:46:00] Starting 'watch-html'...
Failed to fetch extension, trying 4 more times
Failed to fetch extension, trying 3 more times
Failed to fetch extension, trying 2 more times
Failed to fetch extension, trying 1 more times
Failed to fetch extension, trying 0 more times
Error installing REACT_DEVELOPER_TOOLS extension: net::ERR_TUNNEL_CONNECTION_FAILED
Failed to fetch extension, trying 4 more times
Failed to fetch extension, trying 3 more times
Failed to fetch extension, trying 2 more times
Failed to fetch extension, trying 1 more times
Failed to fetch extension, trying 0 more times
Error installing REDUX_DEVTOOLS extension: net::ERR_TUNNEL_CONNECTION_FAILED
(electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397

**Comment by wildorwilliamgit** [comment] 2020-10-02 08:57
I think the errors was related to REACT_DEVELOPER_TOOLS extension, so these are no relation to empty results. Because these are only for debugging react apps.
I have already installed npm dependencies including electron, when installing npm, I can't see any errors.

In fact, after cloning your repo, it works fine. I can see the login button in electron app.
But after making some changes to your project, I can't see any result including login button.
So I tried to clone again, but can't still see any result from electron app.
It's really weird.

**Comment by pronebird** [comment] 2020-10-02 09:13
It looks like the issue is related to the failure to install the dev extensions, namely redux devtools. 

As the error code suggests, it is a connectivity error: `net::ERR_TUNNEL_CONNECTION_FAILED`

Try restarting the app & update dev dependencies if needed. I don’t have computer handy to verify but last time I checked it all worked fine.

I am closing this issue since there is nothing we can do to fix this.

If the changes you have made cause the issues then I suggest you to ask for help on stackoverflow.

Cheers,
Andrej

**Comment by wildorwilliamgit** [comment] 2020-10-03 02:57
Hello.
Thanks for your response.
As you mentioned to me, I followed your opinion. So I fixed the errors related to "net::ERR_TUNNEL_CONNECTION_FAILED"
But I can't see any ui from there, can only electron window which is empty.

Could you upload the npm_modules to this repo?
I think it's directly related to the node_module and version problems.
Thanks for your help.
Wildorwilliam.

**Comment by pronebird** [comment] 2020-10-03 06:59
It’s difficult to debug this issue as I don’t have much information to work with.

Could you try cloning the repo at a new location on your disk, then run `npm install` & finally open the command prompt and run `npm run develop`.

Please post any errors you see.

**Comment by wildorwilliamgit** [comment] 2020-10-08 07:52
1)Thanks for your response.
Finally, I have installed electron manually as the www.electron.org site guided.

2)Because I think you are electron expert, I want to know your valuable opinion.
It's very easy for you to answer it.
Sorry...
I have already made website using react as frontend, laravel as backend.
I am going to convert the website(frontend) to desktop app using electron.
For this case, I found out there are loadURL method in electron. 
So if I use this method, then there aren't any code to implement the frontend in my electron code.
I could see the frontend after used loadURL method.
I am confused.
In frontend, I am getting api from laravel backend.
When making desktop application for frontend, should I include the frontend code, or not?
If yes, Why? maybe for speed?
If you were I, which method do you choose?

Sorry for my clumsy question. Thanks.

**Closed** 2020-10-08 08:23 UTC

**Comment by pronebird** [comment] 2020-10-08 08:28
Normally, you do not need to install Electron manually. `npm install` should install Electron under `node_modules/`. All scripts in the `package.json` should take care of calling it properly from the local installation.

As per your question, you should ask on stackoverflow or similar networks to get a detailed answer. 

The GitHub issues are meant to be used for discussions related to the boilerplate.
